Task #1

# Investor  (50000) -----> Bank1 (5%)  ------ ? initially
#                   -----> Bank2 (7%)  ------ ? initially
#                   -----> Bank3(6 %)  ------ ? initially
#
# Income ----- Bank1 + Bank2 = 2250
#        ----- Bank1 + Bank3 = 1400
#
# 1x + 1y + 1z = 50000
# 0.05x + 0.07y + 0z = 2250
# 0.05x + 0z + 0.06z = 1400


# Result = 10000. - Bank1
#          25000. - Bank2
#          15000. - Bank3

In [1]:
import numpy as np

In [2]:
a = np.matrix("1,1,1;0.05,0.07,0;0.05, 0, 0.06")
b = np.matrix("50000;2250;1400")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)

In [3]:
x

matrix([[10000.],
        [25000.],
        [15000.]])

Task#2

# ---IPhone 6   --        x
# ---IPhone 11  --        y
# ---IPhone 12  --        z
# __________________________________all: 1328
#
# x + y + z = 1328               1x + 1y + 1z = 1328
# x = y - 120          ===>      1x + (-1)y + 0z = -120
# x = z + 100                    1x + 0y + (-1)z = 100

#Result:
#---IPhone 6   --         436
# ---IPhone 11  --        556
# ---IPhone 12  --        336

In [4]:
import numpy as np

In [5]:
a = np.matrix("1,1,1;1,-1,0;1, 0, -1")
b = np.matrix("1328;-120;100")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)

In [6]:
x

matrix([[436.],
        [556.],
        [336.]])

Check Result

In [9]:
x.sum()

1328.0000000000002

Task #3

In [10]:
import numpy as np


#Define the three points as NumPy arrays:

In [12]:
A = np.array([np.sqrt(3), 0, np.sqrt(3)])
B = np.array([np.sqrt(6), 0.5, 0])
C = np.array([1, 1/np.sqrt(3), 1])

#Calculate the midpoints of the line segments AB, AC, and BC:

In [15]:
MAB = (A + B) / 2
MAC = (A + C) / 2
MBC = (B + C) / 2

#Calculate the direction vectors of the line segments AB, AC, and BC:

In [16]:
u = B - A
v = C - A
w = C - B

#Calculate the normal vector of the plane containing the points A, B, and C:

In [17]:
n = np.cross(u, v)

#Calculate the coefficients of the quadratic equation defining the ellipsoid:

In [19]:
alpha = np.dot(u, u)
beta = np.dot(v, v)
gamma = np.dot(w, w)
delta = 2 * np.dot(u, v * np.dot(w, n))
epsilon = 2 * np.dot(u, w * np.dot(v, n))
zeta = 2 * np.dot(v, w * np.dot(u, n))

#Calculate the center of the ellipsoid:

In [20]:
D = np.linalg.solve(np.array([[alpha, delta/2, epsilon/2], [delta/2, beta, zeta/2], [epsilon/2, zeta/2, gamma]]), np.array([np.dot(A, A) - np.dot(MAB, MAB), np.dot(B, B) - np.dot(MBC, MBC), np.dot(C, C) - np.dot(MAC, MAC)]))

#Calculate the radii of the ellipsoid:

In [21]:
a = np.sqrt((np.dot(D-MAB,u)**2 + np.dot(D-MAB,v)**2 + np.dot(D-MAB,w)**2) / alpha)
b = np.sqrt((np.dot(D-MBC,u)**2 + np.dot(D-MBC,v)**2 + np.dot(D-MBC,w)**2) / beta)
c = np.sqrt((np.dot(D-MAC,u)**2 + np.dot(D-MAC,v)**2 + np.dot(D-MAC,w)**2) / gamma)

In [22]:
print (f' a**2 = {a**2}, b**2 = {b**2}, c**2 = {c**2}')

 a**2 = 4.444192424191531, b**2 = 7.3946844040876964, c**2 = 6.478400579961988


In [23]:
print(f"(x - {D[0]})**2/{a**2} + (y - {D[1]})**2/{b**2} + (z - {D[2]})**2/{c**2} = 1")

(x - 0.21679698739113096)**2/4.444192424191531 + (y - 1.9464989199403104)**2/7.3946844040876964 + (z - -0.4770032509095099)**2/6.478400579961988 = 1


Task #4

In [24]:
import numpy as np

# Define the three points as NumPy arrays:

In [25]:
A = np.array([1, 12])
B = np.array([3, 54])
C = np.array([-1, 2])

In [26]:
init_matrix = np.matrix([A,B, C])

In [27]:
transpon_matrix = init_matrix.T

In [28]:
x =  np.squeeze(np.asarray(transpon_matrix[0]))
y =  np.squeeze(np.asarray(transpon_matrix[1]))

# Find the coefficients of the quadratic function that fits the points

In [29]:
coefficients = np.polyfit(x, y, 2)

In [30]:
coefficients

array([4., 5., 3.])

Task #5

In [31]:
import numpy as np

In [32]:
def get_polynom(coords):
    n = len(coords)
    x = [c[0] for c in coords]
    y = [c[1] for c in coords]
    a = np.ones((n, n))

    # calc x matrix
    for i in range(len(x)): # row
        for j in range(1, len(x)): # colon

            a[i][j] = pow(x[i],j)

    # calc y matrix
    text_to_b = ''
    for item in y:

        text_item = f'{item};'
        text_to_b += text_item

    text_to_b = text_to_b[:-1]
    b = np.matrix(text_to_b)

    # calc coeficients
    return np.linalg.solve(a, b)

In [33]:
coords =  [(-1, 2), (0, 3), (3, 4), (5, 0)]

In [34]:
get_polynom(coords)

matrix([[ 3.        ],
        [ 0.98333333],
        [-0.06666667],
        [-0.05      ]])